---
- name: First Playbook
  hosts: linuxservers
  become: true

  tasks:
    - name: Create file
      ansible.builtin.file:
        path: /root/testfile2.txt
        state: touch
        mode: '0755'
